language: node_js
node_js:
  - 8
  - 10
  - 12
  - 13
script:
  - |
    # Test the es5 build if the node version is less than 10
    if [ $(node -v | cut -d'.' -f1 | tr -d 'v') -lt 10 ]; then
      npm run test:es5
    else
      npm test
    fi
notifications:
  email: false
  _webhooks: _
