name: ExcelJS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    name: Node v${{ matrix.node-version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      # - run: npm test
      #   env:
      #     CI: true

  typescript:
    name: Ensure typescript compatibility
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Create the npm cache directory
        run: mkdir npm-cache && npm config set cache ./npm-cache --global
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ./npm-cache
          key: v1-npm-${{ hashFiles('**/package.json') }}
          restore-keys: |
            v1-npm-
      - run: npm install
      - run: npm install typescript
      - run: tsc index.d.ts
        env:
          CI: true
