name: ensure-green-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Testing on node v${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: |
        # Test the es5 build if the node version is less than 10
        if [ $(node -v | cut -d'.' -f1 | tr -d 'v') -lt 10 ]; then
          npm run test:es5
        else
          npm test
        fi
    - run: npm install typescript
    - run: tsc index.d.ts
      env:
        CI: true
